version: '3.9'

services:
#  database:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: Kolmakov
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"


  student_service:
    restart: on-failure
    container_name: student_service
    build: student_service/
    ports:
      - "8000:80"
#    depends_on:
#      - database

  teacher_service:
    restart: on-failure
    container_name: teacher_service
    build: teacher_service/
    ports:
      - "8001:80"
#    depends_on:
#      - database
